/* Admin actions are guarded by profiles.role and re-enforced by database RLS/storage policies. */
document.addEventListener('DOMContentLoaded',async()=>{
 const root=document.querySelector('[data-page="admin"]');if(!root||!window.supabaseClient)return;
 const sb=window.supabaseClient,$=s=>document.querySelector(s);
 const say=(id,msg,bad=false)=>{const e=$('#'+id);if(e){e.textContent=msg;e.dataset.error=String(bad);}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const {data:{user},error:authError}=await sb.auth.getUser();
 if(authError||!user){location.replace('/auth.html?next='+encodeURIComponent('/admin-portal.html'));return;}
 const {data:profile,error:profileError}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();
 if(profileError||profile?.role!=='admin'){location.replace('/client-dashboard.html');return;}
 let projects=[],clients=[];
 async function loadAll(){
  const [c,p,q,i]=await Promise.all([
   sb.from('profiles').select('id,full_name,company_name,created_at').eq('role','client').order('created_at',{ascending:false}).limit(100),
   sb.from('projects').select('id,client_id,title,status,progress,due_date').order('updated_at',{ascending:false}).limit(200),
   sb.from('proposals').select('id,client_id,title,description,budget,timeline,status,created_at').order('created_at',{ascending:false}).limit(200),
   sb.from('invoices').select('id,status').in('status',['pending','overdue'])
  ]);
  for(const r of [c,p,q,i])if(r.error)throw r.error;
  clients=c.data||[];projects=p.data||[];
  $('[data-admin-clients]').textContent=clients.length;$('[data-admin-projects]').textContent=projects.length;
  $('[data-admin-proposals]').textContent=(q.data||[]).filter(x=>['submitted','reviewing','quoted'].includes(x.status)).length;
  $('[data-admin-invoices]').textContent=(i.data||[]).length;
  $('[data-admin-client-list]').innerHTML=clients.length?clients.map(c=>'<tr><td>'+esc(c.full_name||'Unnamed client')+'</td><td>'+esc(c.company_name||'—')+'</td><td>'+esc(c.created_at?new Date(c.created_at).toLocaleDateString():'—')+'</td></tr>').join(''):'<tr><td colspan="3">No client accounts found.</td></tr>';
  $('#invoice-client').innerHTML='<option value="">Choose client…</option>'+clients.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.full_name||'Unnamed client')+' · '+esc(c.id.slice(0,8))+'</option>').join('');
  $('[data-admin-project-list]').innerHTML=projects.length?projects.map(p=>'<tr><td><strong>'+esc(p.title)+'</strong><small>'+esc(p.id)+'</small></td><td><small>'+esc(p.client_id)+'</small></td><td>'+esc(p.status)+'</td><td>'+Number(p.progress||0)+'%</td><td><button class="button" type="button" data-fill-project="'+esc(p.id)+'">Use ID</button></td></tr>').join(''):'<tr><td colspan="5">No projects yet.</td></tr>';
  $('[data-admin-proposal-list]').innerHTML=(q.data||[]).length?(q.data||[]).map(p=>'<tr><td><strong>'+esc(p.title)+'</strong><small>'+esc(p.description)+'</small></td><td>'+esc(p.budget==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(p.budget)))+'</td><td>'+esc(p.timeline||'—')+'</td><td><select data-proposal-status="'+esc(p.id)+'">'+['submitted','reviewing','quoted','accepted','declined','converted'].map(s=>'<option value="'+s+'" '+(s===p.status?'selected':'')+'>'+s+'</option>').join('')+'</select></td><td>'+esc(p.created_at?new Date(p.created_at).toLocaleDateString():'—')+'</td></tr>').join(''):'<tr><td colspan="5">No proposals submitted yet.</td></tr>';
 }
 try{await loadAll();}catch(e){const el=$('[data-error-message]');el.hidden=false;el.textContent='Could not load admin data: '+e.message;}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-fill-project]');if(!b)return;const id=b.dataset.fillProject;['#project-id','#milestone-project-id','#deliverable-project-id','#invoice-project'].forEach(sel=>{const el=$(sel);if(el)el.value=id;});say('admin-message','Project ID filled into the status form.');});
 $('#admin-project-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]');btn.disabled=true;try{const id=f.elements.project_id.value.trim();if(!projects.some(p=>p.id===id))throw new Error('Choose a project ID from the list below.');const {error}=await sb.from('projects').update({status:f.elements.status.value,progress:Number(f.elements.progress.value),updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;say('admin-message','Project updated.');await loadAll();}catch(err){say('admin-message','Update failed: '+err.message,true);}finally{btn.disabled=false;}});
 $('#admin-milestone-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]');btn.disabled=true;try{const id=f.elements.project_id.value.trim();if(!projects.some(p=>p.id===id))throw new Error('Choose a project ID from the list below.');const {error}=await sb.from('milestones').insert({project_id:id,title:f.elements.title.value.trim(),description:f.elements.description.value.trim(),status:f.elements.status.value,progress:Number(f.elements.progress.value),due_date:f.elements.due_date.value||null});if(error)throw error;say('milestone-message','Milestone created.');f.reset();f.elements.progress.value=0;}catch(err){say('milestone-message','Could not create milestone: '+err.message,true);}finally{btn.disabled=false;}});
 $('#admin-deliverable-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]'),file=f.elements.file.files[0];btn.disabled=true;try{const projectId=f.elements.project_id.value.trim();if(!projects.some(p=>p.id===projectId))throw new Error('Choose a project ID from the list below.');if(!file)throw new Error('Choose a file to upload.');if(file.size>50*1024*1024)throw new Error('Files must be 50 MB or smaller.');const allowed=['application/pdf','image/png','image/jpeg','image/webp','application/zip','text/plain'];if(!allowed.includes(file.type))throw new Error('That file type is not supported.');const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-140);const storagePath=projectId+'/'+crypto.randomUUID()+'-'+safeName;const {error:uploadError}=await sb.storage.from('client-deliverables').upload(storagePath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {error:rowError}=await sb.from('deliverables').insert({project_id:projectId,title:f.elements.title.value.trim(),description:f.elements.description.value.trim(),file_url:storagePath,status:'ready'});if(rowError){await sb.storage.from('client-deliverables').remove([storagePath]);throw rowError;}say('deliverable-message','File uploaded privately and shared with the project client.');f.reset();}catch(err){say('deliverable-message','Upload failed: '+err.message,true);}finally{btn.disabled=false;}});
 $('#admin-invoice-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]');btn.disabled=true;try{const projectId=f.elements.project_id.value.trim()||null;if(projectId&&!projects.some(p=>p.id===projectId))throw new Error('Project ID was not found in the project list.');const paymentUrl=f.elements.payment_url.value.trim()||null;if(paymentUrl&&!/^https:\/\//i.test(paymentUrl))throw new Error('Payment links must use HTTPS.');const {error}=await sb.from('invoices').insert({client_id:f.elements.client_id.value,project_id:projectId,invoice_number:f.elements.invoice_number.value.trim(),description:f.elements.description.value.trim(),amount:Number(f.elements.amount.value),currency:'INR',status:'pending',due_at:f.elements.due_at.value?new Date(f.elements.due_at.value+'T23:59:59').toISOString():null,payment_url:paymentUrl});if(error)throw error;say('invoice-message','Invoice created. It is now visible in the selected client’s billing tab.');f.reset();}catch(err){say('invoice-message','Could not create invoice: '+err.message,true);}finally{btn.disabled=false;}});
 $('[data-admin-proposal-list]').addEventListener('change',async e=>{const sel=e.target.closest('[data-proposal-status]');if(!sel)return;sel.disabled=true;try{const {error}=await sb.from('proposals').update({status:sel.value,updated_at:new Date().toISOString()}).eq('id',sel.dataset.proposalStatus);if(error)throw error;say('admin-message','Proposal status updated.');await loadAll();}catch(err){say('admin-message','Proposal update failed: '+err.message,true);}finally{sel.disabled=false;}});
 function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
});