/* Admin actions are guarded by profiles.role and re-enforced by database RLS/storage policies. */
document.addEventListener('DOMContentLoaded',async()=>{
 const root=document.querySelector('[data-page="admin"]');if(!root||!window.supabaseClient)return;
 const sb=window.supabaseClient,$=s=>document.querySelector(s);
 const say=(id,msg,bad=false)=>{const e=$('#'+id);if(e){e.textContent=msg;e.dataset.error=String(bad);}};
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const {data:{user},error:authError}=await sb.auth.getUser();
 if(authError||!user){location.replace('/auth.html?next='+encodeURIComponent('/admin-portal.html'));return;}
 const {data:profile,error:profileError}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();
 if(profileError||profile?.role!=='admin'){location.replace('/client-dashboard.html');return;}
 let projects=[],clients=[],leads=[];

 function renderLeads(){
  const term=($('#admin-lead-search')?.value||'').trim().toLowerCase();
  const filtered=leads.filter(x=>[x.name,x.email,x.whatsapp,x.project_type,x.description,x.status].join(' ').toLowerCase().includes(term));
  const count=$('#admin-lead-count');if(count)count.textContent=filtered.length+' of '+leads.length+' requests';
  const body=$('[data-admin-lead-list]');if(!body)return;
  const states=['New','Reviewing','Contacted','Converted','Closed'];
  body.innerHTML=filtered.length?filtered.map(x=>{const status=states.find(s=>s.toLowerCase()===String(x.status||'New').toLowerCase())||'New';return '<tr><td><strong>'+esc(x.name||'Unnamed visitor')+'</strong><small>'+esc(x.email||'No email')+'</small>'+(x.whatsapp?'<small>'+esc(x.whatsapp)+'</small>':'')+'</td><td><strong>'+esc(x.project_type||'General enquiry')+'</strong><details style="max-width:360px"><summary style="cursor:pointer;font-size:12px">Read project brief</summary><p style="white-space:pre-wrap;overflow-wrap:anywhere">'+esc(x.description||'No description supplied')+'</p></details></td><td>'+esc(x.budget_range||'Not specified')+'<small>Due: '+esc(x.deadline||'Not specified')+'</small></td><td>'+esc(x.created_at?new Date(x.created_at).toLocaleString():'—')+'</td><td><select aria-label="Update request status" data-lead-status="'+esc(x.id)+'">'+states.map(s=>'<option value="'+s+'" '+(s===status?'selected':'')+'>'+s+'</option>').join('')+'</select></td></tr>';}).join(''):'<tr><td colspan="5">No project requests match this search.</td></tr>';
 }
 async function loadAll(){
  const [c,p,q,i,m,l]=await Promise.all([
   sb.from('profiles').select('id,full_name,company_name,created_at').eq('role','client').order('created_at',{ascending:false}).limit(100),
   sb.from('projects').select('id,client_id,title,status,progress,due_date').order('updated_at',{ascending:false}).limit(200),
   sb.from('proposals').select('id,client_id,title,description,budget,timeline,status,created_at').order('created_at',{ascending:false}).limit(200),
   sb.from('invoices').select('id,client_id,status').in('status',['pending','overdue']),
   sb.from('milestones').select('id,project_id,title,status,progress,due_date,sort_order').order('sort_order',{ascending:true}).limit(500),
   sb.from('leads').select('id,name,email,whatsapp,project_type,budget_range,deadline,description,status,created_at,user_id,client_email').order('created_at',{ascending:false}).limit(300)
  ]);
  for(const r of [c,p,q,i,m,l])if(r.error)throw r.error;
  clients=c.data||[];projects=p.data||[];leads=l.data||[];const milestoneRows=m.data||[];
  $('[data-admin-clients]').textContent=clients.length;$('[data-admin-projects]').textContent=projects.length;
  $('[data-admin-proposals]').textContent=(q.data||[]).filter(x=>['submitted','reviewing','quoted'].includes(x.status)).length;
  $('[data-admin-invoices]').textContent=(i.data||[]).length;
  $('[data-admin-client-list]').innerHTML=clients.length?clients.map(c=>'<tr><td>'+esc(c.full_name||'Unnamed client')+'</td><td>'+esc(c.company_name||'—')+'</td><td>'+projects.filter(p=>p.client_id===c.id).length+'</td><td>'+(i.data||[]).filter(inv=>inv.client_id===c.id).length+'</td><td>'+esc(c.created_at?new Date(c.created_at).toLocaleDateString():'—')+'</td></tr>').join(''):'<tr><td colspan="5">No client accounts found.</td></tr>';
  $('#invoice-client').innerHTML='<option value="">Choose client…</option>'+clients.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.full_name||'Unnamed client')+' · '+esc(c.id.slice(0,8))+'</option>').join('');
  $('[data-admin-milestone-list]').innerHTML=milestoneRows.length?milestoneRows.map(m=>'<tr><td><strong>'+esc(m.title)+'</strong><small>'+esc(m.id)+'</small></td><td><small>'+esc(m.project_id)+'</small></td><td><select data-milestone-status="'+esc(m.id)+'">'+['pending','in_progress','submitted_for_approval','approved','completed'].map(s=>'<option value="'+s+'" '+(s===m.status?'selected':'')+'>'+s+'</option>').join('')+'</select></td><td><input aria-label="Milestone progress" data-milestone-progress="'+esc(m.id)+'" type="number" min="0" max="100" value="'+Number(m.progress||0)+'" style="width:72px;padding:8px;border:1px solid var(--portal-line);border-radius:8px"></td><td>'+esc(m.due_date||'—')+'</td><td><button class="button" type="button" data-save-milestone="'+esc(m.id)+'">Save</button></td></tr>').join(''):'<tr><td colspan="6">No milestones created yet.</td></tr>';$('[data-admin-project-list]').innerHTML=projects.length?projects.map(p=>'<tr><td><strong>'+esc(p.title)+'</strong><small>'+esc(p.id)+'</small></td><td><small>'+esc(p.client_id)+'</small></td><td>'+esc(p.status)+'</td><td>'+Number(p.progress||0)+'%</td><td><button class="button" type="button" data-fill-project="'+esc(p.id)+'">Use ID</button></td></tr>').join(''):'<tr><td colspan="5">No projects yet.</td></tr>';
  renderLeads();
  $('[data-admin-proposal-list]').innerHTML=(q.data||[]).length?(q.data||[]).map(p=>'<tr><td><strong>'+esc(p.title)+'</strong><small>'+esc(p.description)+'</small></td><td>'+esc(p.budget==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(p.budget)))+'</td><td>'+esc(p.timeline||'—')+'</td><td><select data-proposal-status="'+esc(p.id)+'">'+['submitted','reviewing','quoted','accepted','declined','converted'].map(s=>'<option value="'+s+'" '+(s===p.status?'selected':'')+'>'+s+'</option>').join('')+'</select></td><td>'+esc(p.created_at?new Date(p.created_at).toLocaleDateString():'—')+'</td></tr>').join(''):'<tr><td colspan="5">No proposals submitted yet.</td></tr>';
 }
 try{await loadAll();}catch(e){const el=$('[data-error-message]');el.hidden=false;el.textContent='Could not load admin data: '+e.message;}
 $('#admin-lead-search')?.addEventListener('input',renderLeads);
 $('[data-admin-lead-list]')?.addEventListener('change',async e=>{const select=e.target.closest('[data-lead-status]');if(!select)return;const old=leads.find(x=>x.id===select.dataset.leadStatus)?.status||'New';select.disabled=true;try{const {error}=await sb.from('leads').update({status:select.value,updated_at:new Date().toISOString()}).eq('id',select.dataset.leadStatus);if(error)throw error;say('lead-message','Project request status updated.');await loadAll();}catch(err){say('lead-message','Could not update request status: '+err.message,true);select.value=old;}finally{select.disabled=false;}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-fill-project]');if(!b)return;const id=b.dataset.fillProject;['#project-id','#milestone-project-id','#deliverable-project-id','#invoice-project'].forEach(sel=>{const el=$(sel);if(el)el.value=id;});say('admin-message','Project ID filled into the status form.');});
 $('#admin-project-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]');btn.disabled=true;try{const id=f.elements.project_id.value.trim();if(!projects.some(p=>p.id===id))throw new Error('Choose a project ID from the list below.');const {error}=await sb.from('projects').update({status:f.elements.status.value,progress:Number(f.elements.progress.value),updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;say('admin-message','Project updated.');await loadAll();}catch(err){say('admin-message','Update failed: '+err.message,true);}finally{btn.disabled=false;}});
 $('#admin-milestone-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]');btn.disabled=true;try{const id=f.elements.project_id.value.trim();if(!projects.some(p=>p.id===id))throw new Error('Choose a project ID from the list below.');const {error}=await sb.from('milestones').insert({project_id:id,title:f.elements.title.value.trim(),description:f.elements.description.value.trim(),status:f.elements.status.value,progress:Number(f.elements.progress.value),due_date:f.elements.due_date.value||null});if(error)throw error;say('milestone-message','Milestone created.');f.reset();f.elements.progress.value=0;await loadAll();}catch(err){say('milestone-message','Could not create milestone: '+err.message,true);}finally{btn.disabled=false;}});
 $('#admin-deliverable-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]'),file=f.elements.file.files[0];btn.disabled=true;try{const projectId=f.elements.project_id.value.trim();if(!projects.some(p=>p.id===projectId))throw new Error('Choose a project ID from the list below.');if(!file)throw new Error('Choose a file to upload.');if(file.size>50*1024*1024)throw new Error('Files must be 50 MB or smaller.');const ext=(file.name.split('.').pop()||'').toLowerCase();const allowedTypes=['application/pdf','image/png','image/jpeg','image/webp','application/zip','application/x-zip-compressed','text/plain'];if(!allowedTypes.includes(file.type)&&!['pdf','png','jpg','jpeg','webp','zip','txt'].includes(ext))throw new Error('That file type is not supported.');const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-140);const storagePath=projectId+'/'+crypto.randomUUID()+'-'+safeName;const {error:uploadError}=await sb.storage.from('client-deliverables').upload(storagePath,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {error:rowError}=await sb.from('deliverables').insert({project_id:projectId,title:f.elements.title.value.trim(),description:f.elements.description.value.trim(),file_url:storagePath,status:'ready'});if(rowError){await sb.storage.from('client-deliverables').remove([storagePath]);throw rowError;}say('deliverable-message','File uploaded privately and shared with the project client.');f.reset();}catch(err){say('deliverable-message','Upload failed: '+err.message,true);}finally{btn.disabled=false;}});
 $('#admin-invoice-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,btn=f.querySelector('[type=submit]');btn.disabled=true;try{const projectId=f.elements.project_id.value.trim()||null;const selectedClient=f.elements.client_id.value;if(projectId&&!projects.some(p=>p.id===projectId))throw new Error('Project ID was not found in the project list.');if(projectId&&projects.find(p=>p.id===projectId)?.client_id!==selectedClient)throw new Error('The selected project belongs to a different client.');const paymentUrl=f.elements.payment_url.value.trim()||null;if(paymentUrl&&!/^https:\/\//i.test(paymentUrl))throw new Error('Payment links must use HTTPS.');const {error}=await sb.from('invoices').insert({client_id:f.elements.client_id.value,project_id:projectId,invoice_number:f.elements.invoice_number.value.trim(),description:f.elements.description.value.trim(),amount:Number(f.elements.amount.value),currency:'INR',status:'pending',due_at:f.elements.due_at.value?new Date(f.elements.due_at.value+'T23:59:59').toISOString():null,payment_url:paymentUrl});if(error)throw error;say('invoice-message','Invoice created. It is now visible in the selected client’s billing tab.');f.reset();await loadAll();}catch(err){say('invoice-message','Could not create invoice: '+err.message,true);}finally{btn.disabled=false;}});
 $('[data-admin-milestone-list]').addEventListener('click',async e=>{const btn=e.target.closest('[data-save-milestone]');if(!btn)return;btn.disabled=true;try{const id=btn.dataset.saveMilestone,status=$('[data-milestone-status="'+id+'"]').value,progress=Number($('[data-milestone-progress="'+id+'"]').value);const {error}=await sb.from('milestones').update({status,progress}).eq('id',id);if(error)throw error;say('milestone-message','Milestone updated.');await loadAll();}catch(err){say('milestone-message','Could not update milestone: '+err.message,true);}finally{btn.disabled=false;}});
 const preview=$('#admin-client-preview');$('[data-open-client-preview]')?.addEventListener('click',()=>{preview.hidden=false;preview.querySelector('[data-close-client-preview]')?.focus();});preview?.querySelectorAll('[data-close-client-preview]').forEach(b=>b.addEventListener('click',()=>preview.hidden=true));preview?.addEventListener('click',e=>{if(e.target===preview)preview.hidden=true;});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&preview&&!preview.hidden)preview.hidden=true;});
 $('[data-admin-proposal-list]').addEventListener('change',async e=>{const sel=e.target.closest('[data-proposal-status]');if(!sel)return;sel.disabled=true;try{const {error}=await sb.from('proposals').update({status:sel.value,updated_at:new Date().toISOString()}).eq('id',sel.dataset.proposalStatus);if(error)throw error;say('admin-message','Proposal status updated.');await loadAll();}catch(err){say('admin-message','Proposal update failed: '+err.message,true);}finally{sel.disabled=false;}});

});