/* Real Supabase Auth controller. No mock JWTs or credentials in localStorage.
   "Remember me" selects session persistence; Supabase manages token storage/refresh. */
(() => {
  class Emitter {
    constructor(){this.events=new Map();}
    on(type,fn){if(!this.events.has(type))this.events.set(type,new Set());this.events.get(type).add(fn);return()=>this.events.get(type)?.delete(fn);}
    emit(type,payload){for(const fn of this.events.get(type)||[])try{fn(payload);}catch(e){console.error(e);}}
  }
  function safeNextPath(){const next=new URLSearchParams(location.search).get('next');return next&&next.startsWith('/')&&!next.startsWith('//')&&!next.includes('\\')&&!/^\/(?:auth(?:\.html)?|login)(?:[/?#]|$)/i.test(next)?next:'/welcome.html';}
  window.AuthState = new Emitter();
  window.AuthState.snapshot = {isLoggedIn:false,userRole:null,token:null,profileData:null};
  class AuthManager {
    constructor(sb){this.sb=sb;this.authSubscription=null;this.mode='login';this.form=document.querySelector('#auth-form');this.message=document.querySelector('#auth-message');this.submit=document.querySelector('#auth-submit');this.bind();this.observe();}
    say(text,error=false){this.message.hidden=!text;this.message.textContent=text||'';this.message.dataset.error=String(error);}
    setMode(mode){if(mode==='register'){this.mode='login';this.say('Client accounts are invitation-only. Use the invitation sent after a project is accepted.');return;}this.mode=mode;document.querySelectorAll('[data-auth-tab]').forEach(b=>{const active=b.dataset.authTab===mode;b.classList.toggle('button-dark',active);b.setAttribute('aria-selected',String(active));});document.querySelector('[data-auth-name]').hidden=mode!=='register';document.querySelector('[data-auth-name] input').required=mode==='register';document.querySelector('[data-auth-password]').hidden=mode==='reset';document.querySelector('[data-remember]').hidden=mode!=='login';const pw=this.form.elements.password;pw.required=mode!=='reset';pw.autocomplete=mode==='register'?'new-password':'current-password';this.submit.textContent=({login:'Log in ↗',register:'Create account ↗',reset:'Send reset link ↗'})[mode];this.say('');}
    bind(){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>this.setMode(b.dataset.authTab)));this.form.addEventListener('submit',e=>{e.preventDefault();this.submitForm();});this.form.elements.password.addEventListener('input',e=>this.passwordMeter(e.target.value));document.querySelectorAll('[data-oauth]').forEach(b=>b.addEventListener('click',()=>this.oauth(b.dataset.oauth)));}
    passwordMeter(value){const score=[value.length>=8,/[a-z]/.test(value)&&/[A-Z]/.test(value),/\d/.test(value),/[^A-Za-z0-9]/.test(value)].filter(Boolean).length;document.querySelector('#password-strength').style.width=(score*25)+'%';document.querySelector('#password-hint').textContent=value.length===0?'Use at least 8 characters.':score<2?'Weak password':score<4?'Good — add variety':'Strong password';}
    observe(){this.authSubscription?.unsubscribe();this.authSubscription=null;const client=this.sb;client.auth.getUser().then(({data:{user}})=>{if(client===this.sb&&user)this.publishUser(user);}).catch(e=>console.warn('Session check failed:',e));const {data:{subscription}}=client.auth.onAuthStateChange((event,session)=>{if(client!==this.sb)return;if(session?.user){Promise.resolve().then(()=>{if(client===this.sb)this.publishUser(session.user,session.access_token);});}else{window.AuthState.snapshot={isLoggedIn:false,userRole:null,token:null,profileData:null};window.AuthState.emit('change',window.AuthState.snapshot);}});this.authSubscription=subscription;}
    async publishUser(user,token=null){const {data:profile,error}=await this.sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)console.warn('Profile fetch:',error.message);const state={isLoggedIn:true,userRole:profile?.role||'client',token,profileData:{...profile,email:user.email,created_at:user.created_at}};window.AuthState.snapshot=state;window.AuthState.emit('change',state);}
    async submitForm(){const email=this.form.elements.email.value.trim();const password=this.form.elements.password.value;this.submit.disabled=true;this.say('Please wait…');try{let result;if(this.mode!=='reset')this.preparePersistence();if(this.mode==='login'){result=await this.sb.auth.signInWithPassword({email,password});if(result.error)throw result.error;location.assign(safeNextPath());return;}if(this.mode==='register'){throw new Error('Client accounts are invitation-only. Use the invitation sent after a project is accepted.');}result=await this.sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/reset-password.html'});if(result.error)throw result.error;this.say('If an account exists for that email, password reset instructions have been sent.');}catch(e){this.say(e.message||'Authentication failed. Please try again.',true);}finally{this.submit.disabled=false;}}
    preparePersistence(attachObserver=true){const remember=this.form.elements.remember?.checked!==false;document.cookie='portal_session='+(remember?'0':'1')+'; Path=/; SameSite=Lax; Secure'+(remember?'; Max-Age=31536000':'');if(window.createPortalSupabaseClient){this.sb=window.createPortalSupabaseClient(remember);window.supabaseClient=this.sb;if(attachObserver)this.observe();}}
    async oauth(provider){const buttons=[...document.querySelectorAll('[data-oauth]')];buttons.forEach(b=>b.disabled=true);const label=({google:'Google',github:'GitHub',linkedin_oidc:'LinkedIn'})[provider]||provider;this.say('Connecting to '+label+'…');try{this.preparePersistence(false);if(!this.sb?.auth?.signInWithOAuth)throw new Error('The authentication client did not load. Reload the page; if it persists, check the Supabase script and site configuration.');const {data,error}=await this.sb.auth.signInWithOAuth({provider,options:{redirectTo:location.origin+'/auth-callback.html',skipBrowserRedirect:true,queryParams:{access_type:'online',prompt:'select_account'}}});if(error)throw error;if(!data?.url)throw new Error('The sign-in provider returned no redirect URL. Check that the provider is enabled in Supabase Auth settings.');this.say('Redirecting to '+label+'…');location.assign(data.url);}catch(e){const msg=String(e?.message||'Sign-in could not start.');this.say(/provider.*not enabled|unsupported provider|provider is disabled/i.test(msg)?label+' sign-in is not enabled yet. Enable it in Supabase → Authentication → Sign In / Providers and add its OAuth credentials.':msg,true);buttons.forEach(b=>b.disabled=false);}}
  }
  function init(){if(!document.querySelector('#auth-form'))return;if(!window.supabaseClient){const m=document.querySelector('#auth-message');m.hidden=false;m.textContent='Supabase configuration is unavailable. Check portal-supabase.js.';return;}window.authManager=new AuthManager(window.supabaseClient);}
  document.addEventListener('DOMContentLoaded',init);
  window.requireAuth=async function(role){const sb=window.supabaseClient;if(!sb){location.assign('/auth.html');return null;}const {data:{user},error}=await sb.auth.getUser();if(error||!user){location.assign('/auth.html?next='+encodeURIComponent(location.pathname));return null;}const {data:profile}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();const actual=profile?.role||'client';if(role&&actual!==role){location.assign(actual==='admin'?'/admin-portal.html':'/client-dashboard.html');return null;}return {user,role:actual};};
})();