/* Real Supabase Auth controller. No mock JWTs or credentials in localStorage.
   "Remember me" selects session persistence; Supabase manages token storage/refresh. */
(() => {
  class Emitter {
    constructor(){this.events=new Map();}
    on(type,fn){if(!this.events.has(type))this.events.set(type,new Set());this.events.get(type).add(fn);return()=>this.events.get(type)?.delete(fn);}
    emit(type,payload){for(const fn of this.events.get(type)||[])try{fn(payload);}catch(e){console.error(e);}}
  }
  window.AuthState = new Emitter();
  window.AuthState.snapshot = {isLoggedIn:false,userRole:null,token:null,profileData:null};
  class AuthManager {
    constructor(sb){this.sb=sb;this.mode='login';this.form=document.querySelector('#auth-form');this.message=document.querySelector('#auth-message');this.submit=document.querySelector('#auth-submit');this.bind();this.observe();}
    say(text,error=false){this.message.hidden=!text;this.message.textContent=text||'';this.message.dataset.error=String(error);}
    setMode(mode){this.mode=mode;document.querySelectorAll('[data-auth-tab]').forEach(b=>{const active=b.dataset.authTab===mode;b.classList.toggle('button-dark',active);b.setAttribute('aria-selected',String(active));});document.querySelector('[data-auth-name]').hidden=mode!=='register';document.querySelector('[data-auth-password]').hidden=mode==='reset';document.querySelector('[data-remember]').hidden=mode!=='login';const pw=this.form.elements.password;pw.required=mode!=='reset';pw.autocomplete=mode==='register'?'new-password':'current-password';this.submit.textContent=({login:'Log in ↗',register:'Create account ↗',reset:'Send reset link ↗'})[mode];this.say('');}
    bind(){document.querySelectorAll('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>this.setMode(b.dataset.authTab)));this.form.addEventListener('submit',e=>{e.preventDefault();this.submitForm();});this.form.elements.password.addEventListener('input',e=>this.passwordMeter(e.target.value));document.querySelectorAll('[data-oauth]').forEach(b=>b.addEventListener('click',()=>this.oauth(b.dataset.oauth)));}
    passwordMeter(value){const score=[value.length>=8,/[a-z]/.test(value)&&/[A-Z]/.test(value),/\d/.test(value),/[^A-Za-z0-9]/.test(value)].filter(Boolean).length;document.querySelector('#password-strength').style.width=(score*25)+'%';document.querySelector('#password-hint').textContent=value.length===0?'Use at least 8 characters.':score<2?'Weak password':score<4?'Good — add variety':'Strong password';}
    async observe(){const {data:{user}}=await this.sb.auth.getUser();if(user)await this.publishUser(user);this.sb.auth.onAuthStateChange(async(event,session)=>{if(session?.user)await this.publishUser(session.user,session.access_token);else{window.AuthState.snapshot={isLoggedIn:false,userRole:null,token:null,profileData:null};window.AuthState.emit('change',window.AuthState.snapshot);}});}
    async publishUser(user,token=null){const {data:profile,error}=await this.sb.from('profiles').select('*').eq('id',user.id).maybeSingle();if(error)console.warn('Profile fetch:',error.message);const state={isLoggedIn:true,userRole:profile?.role||'client',token,profileData:{...profile,email:user.email,created_at:user.created_at}};window.AuthState.snapshot=state;window.AuthState.emit('change',state);}
    async submitForm(){const email=this.form.elements.email.value.trim();const password=this.form.elements.password.value;this.submit.disabled=true;this.say('Please wait…');try{let result;if(this.mode==='login'){result=await this.sb.auth.signInWithPassword({email,password});if(result.error)throw result.error;location.assign(new URLSearchParams(location.search).get('next')||'/welcome.html');return;}if(this.mode==='register'){if(password.length<8)throw new Error('Use a password with at least 8 characters.');result=await this.sb.auth.signUp({email,password,options:{data:{full_name:this.form.elements.full_name.value.trim()}}});if(result.error)throw result.error;if(result.data.session){location.assign('/welcome.html');return;}this.say('Account created. Check your email to confirm your address, then log in.');return;}result=await this.sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/reset-password.html'});if(result.error)throw result.error;this.say('If an account exists for that email, password reset instructions have been sent.');}catch(e){this.say(e.message||'Authentication failed. Please try again.',true);}finally{this.submit.disabled=false;}}
    async oauth(provider){try{const {error}=await this.sb.auth.signInWithOAuth({provider,options:{redirectTo:location.origin+'/welcome.html'}});if(error)throw error;}catch(e){this.say(e.message||'This sign-in provider is not configured yet.',true);}}
  }
  function init(){if(!document.querySelector('#auth-form'))return;if(!window.supabaseClient){const m=document.querySelector('#auth-message');m.hidden=false;m.textContent='Supabase configuration is unavailable. Check portal-supabase.js.';return;}window.authManager=new AuthManager(window.supabaseClient);}
  document.addEventListener('DOMContentLoaded',init);
  window.requireAuth=async function(role){const sb=window.supabaseClient;if(!sb){location.assign('/auth.html');return null;}const {data:{user},error}=await sb.auth.getUser();if(error||!user){location.assign('/auth.html?next='+encodeURIComponent(location.pathname));return null;}const {data:profile}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();const actual=profile?.role||'client';if(role&&actual!==role){location.assign(actual==='admin'?'/admin-portal.html':'/client-dashboard.html');return null;}return {user,role:actual};};
})();