/* Dashboard interaction layer. Reads live records from Supabase; mock fixtures are for UI demos only. */
(() => {
 class DashboardManager {
  constructor(sb){this.sb=sb;this.activeTab='overview';this.data={projects:[],invoices:[],proposals:[]};}
  async load(userId){const jobs=[this.sb.from('projects').select('*').eq('client_id',userId).order('updated_at',{ascending:false}),this.sb.from('invoices').select('*').eq('client_id',userId).order('created_at',{ascending:false}),this.sb.from('proposals').select('*').eq('client_id',userId).order('created_at',{ascending:false})];const [p,i,q]=await Promise.all(jobs);this.data.projects=p.error?[]:p.data||[];this.data.invoices=i.error?[]:i.data||[];this.data.proposals=q.error?[]:q.data||[];return this.data;}
  switchTab(name){this.activeTab=name;document.querySelectorAll('[data-dashboard-tab]').forEach(b=>{const on=b.dataset.dashboardTab===name;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));});document.querySelectorAll('[data-dashboard-panel]').forEach(p=>p.hidden=p.dataset.dashboardPanel!==name);window.AuthState?.emit('dashboard:tab',name);}
  async createProposal(userId,brief){const title=String(brief.title||'').trim(),description=String(brief.description||'').trim();if(title.length<3||description.length<20)throw new Error('Add a title and a brief of at least 20 characters.');const {data,error}=await this.sb.from('proposals').insert({client_id:userId,title,description,budget:brief.budget||null,timeline:brief.timeline||null,status:'submitted'}).select().single();if(error)throw error;this.data.proposals.unshift(data);return data;}
  async approveMilestone(milestoneId){const {data,error}=await this.sb.from('milestones').update({status:'approved',approved_at:new Date().toISOString()}).eq('id',milestoneId).select().single();if(error)throw error;return data;}
  renderProjects(container){container.innerHTML=this.data.projects.length?this.data.projects.map(p=>'<article class="project-row"><div class="project-main"><strong>'+this.escape(p.title||p.name||'Project')+'</strong><span>'+this.escape(p.status||'In progress')+'</span><div class="progress"><i style="width:'+Math.max(0,Math.min(100,Number(p.progress)||0))+'%"></i></div></div><span class="status">'+Math.max(0,Math.min(100,Number(p.progress)||0))+'%</span></article>').join(''):'<p class="muted">No projects assigned yet.</p>';}
  escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
 }
 window.DashboardManager=DashboardManager;
 document.addEventListener('DOMContentLoaded',async()=>{const root=document.querySelector('[data-portal]');if(!root||!window.supabaseClient)return;const {data:{user}}=await window.supabaseClient.auth.getUser();if(!user)return;const manager=new DashboardManager(window.supabaseClient);window.dashboardManager=manager;document.querySelectorAll('[data-dashboard-tab]').forEach(b=>b.addEventListener('click',()=>manager.switchTab(b.dataset.dashboardTab)));});
})();